myshop/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    # post views
    path("", views.post_list, name="post_list"),
    # path("", views.PostListView.as_view(), name="post_list"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    path("search/", views.post_search, name="post_search"),
    # path("recipes/", views.recipe_list, name="recipe_list"),
    # path("recipes/tag/<slug:tag_slug>/", views.recipe_list, name="recipe_list_by_tag"),
    # path("recipes/<int:post_id>/", views.recipe_detail, name="recipe_detail"),
    # path(
    #     "recipes/<int:year>/<int:month>/<int:day>/<slug:recipe>/",
    #     views.recipe_detail,
    #     name="recipe_detail",
    # ),
    # path("recipes/<int:recipe_id>/rate/", views.rate_recipe, name="rate_recipe"),
    # path("recipes/<int:recipe_id>/share/", views.recipe_comment, name="recipe_comment"),
    # path(
    #     "recipes/<int:recipe_id>/comment/", views.recipe_comment, name="recipe_comment"),
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from payment import webhooks

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path(_("cart/"), include("cart.urls", namespace="cart")),
    path(_("orders/"), include("orders.urls", namespace="orders")),
    path(_("payment/"), include("payment.urls", namespace="payment")),
    path(_("coupons/"), include("coupons.urls", namespace="coupons")),
    path("rosetta/", include("rosetta.urls")),
    path(_("account/"), include("account.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path(_("images/"), include("images.urls", namespace="images")),
    path("__debug__/", include("debug_toolbar.urls")),
    path(_("blog/"), include("blog.urls", namespace="blog")),
    path(_("recipes/"), include("recipes.urls", namespace="recipes")),
    path("", include("shop.urls", namespace="shop")),
)
urlpatterns += [
    path("payment/webhook/", webhooks.stripe_webhook, name="stripe-webhook"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/recipes/urls.py
from django.urls import path
from . import views

app_name = "recipes"
urlpatterns = [
    # post views
    path("", views.recipe_list, name="recipe_list"),
    # path("", views.PostListView.as_view(), name="post_list"),
    path("tag/<slug:tag_slug>/", views.recipe_list, name="recipe_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:recipe>/",
        views.recipe_detail,
        name="recipe_detail",
    ),
    path("<int:recipe_id>/rate/", views.rate_recipe, name="rate_recipe"),
    path("<int:recipe_id>/share/", views.recipe_share, name="recipe_share"),
    path("<int:recipe_id>/comment/", views.recipe_comment, name="recipe_comment"),
    path("like/", views.recipe_like, name="recipe_like"),
]

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"
urlpatterns = [
    path("payment-required/", views.payment_required, name="payment_required"),
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
]

myshop/recipes/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.db.models import Avg
from taggit.managers import TaggableManager
from images.models import Image


# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Recipe.Status.PUBLISHED)


class Recipe(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="recipes_recipe",  # user.recipes_recipe
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    # publish = models.DateTimeField(db_default=Now()) # //Database DateTime Now
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status, default=Status.DRAFT)
    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.

    ingredients = models.TextField()
    prep_time = models.IntegerField(help_text="Preparation time in minutes")
    cook_time = models.IntegerField(help_text="Cooking time in minutes")
    # average_rating = models.DecimalField(max_digits=3, decimal_places=2, default=0.0)

    is_premium = models.BooleanField(default=False)  # New field for premium status

    # Many-to-Many relationship for likes (users who liked the recipe)
    users_like = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="recipes_liked", blank=True
    )
    total_likes = models.PositiveIntegerField(default=0)

    images = models.ManyToManyField(
        Image, related_name="recipes", blank=True
    )  # Many-to-many relationship - image.recipes.all() or recipes.images.all()

    tags = TaggableManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    @property
    def average_rating(self):
        return self.ratings.aggregate(average=Avg("score"))["average"] or 0.0

    def __str__(self):
        return f"{self.title} - {self.average_rating:.2f}"

    # Connected to recipe_list.html (recipe.get_absolute_url)
    def get_absolute_url(self):
        return reverse(
            "recipes:recipe_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )

    # def get_absolute_url(self):
    #     return reverse(
    #         "recipes:recipe_detail",
    #         args=[self.id],
    #     )

    # The reverse() function will build the URL dynamically using the URL name defined in the URL patterns.

    # def total_likes_count(self):
    #     return self.users_like.count()


class Rating(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="ratings")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    score = models.PositiveIntegerField(default=1)

    class Meta:
        unique_together = ("recipe", "user")


class RecipeComment(models.Model):
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="recipe_comments"
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=["created"]),
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.recipe}"

myshop/recipes/forms.py
from django import forms

# from .models import Comment
from .models import Recipe, Rating, RecipeComment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["title", "body", "ingredients", "prep_time", "cook_time"]


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["score"]


class RecipeCommentForm(forms.ModelForm):
    class Meta:
        model = RecipeComment
        fields = ["name", "email", "body"]

myshop/recipes/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.http import JsonResponse
from django.http import HttpResponse
from django.http import Http404
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Avg, Count
from django.contrib.postgres.search import (
    SearchVector,
    SearchQuery,
    SearchRank,
    TrigramSimilarity,
)
from taggit.models import Tag

# from .models import Post
from .models import Recipe, Rating
from orders.models import PaidUser

# from .forms import CommentForm, EmailPostForm, SearchForm
from .forms import RecipeCommentForm, RatingForm, EmailPostForm
from actions.utils import create_action

import redis
from django.conf import settings

# connect to redis
r = redis.Redis(
    host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB
)


def recipe_list(request, tag_slug=None):

    # if (
    #     request.user.is_authenticated
    #     and hasattr(request.user, "paid_user")
    #     and request.user.paid_user.is_paid
    # ):
    # Show all recipes to paid users
    recipes_list = Recipe.published.all()
    # else:
    #     # Show only non-premium recipes to non-paid users
    #     recipes_list = Recipe.published.filter(is_premium=False)

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        recipes_list = recipes_list.filter(tags__in=[tag])

    paginator = Paginator(recipes_list, 3)
    page_number = request.GET.get("page", 1)
    try:
        recipes = paginator.page(page_number)
    except PageNotAnInteger:
        # If page_number is not an integer get the first page
        recipes = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range get last page of results
        recipes = paginator.page(paginator.num_pages)
    return render(
        request, "recipes/recipe/recipe_list.html", {"recipes": recipes, "tag": tag}
    )


def recipe_detail(request, year, month, day, recipe):
    recipe = get_object_or_404(
        Recipe,
        status=Recipe.Status.PUBLISHED,
        slug=recipe,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    if recipe.is_premium and not (
        request.user.is_authenticated
        and hasattr(request.user, "paid_user")
        and request.user.paid_user.is_paid
    ):
        return redirect("shop:payment_required")

    # List of active comments for this recipe
    comments = recipe.recipe_comments.filter(active=True)

    form = RecipeCommentForm()  # Create an empty form to render on the page
    # List of similar recipes
    recipe_tags_ids = recipe.tags.values_list("id", flat=True)
    similar_recipes = Recipe.published.filter(tags__in=recipe_tags_ids).exclude(
        id=recipe.id
    )
    similar_recipes = similar_recipes.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:4]

    # Form for users to comment on recipe
    rating_form = RatingForm()
    average_rating = recipe.average_rating

    # increment total image views by 1
    # for redis
    total_views = r.incr(f"recipe:{recipe.id}:views")

    return render(
        request,
        "recipes/recipe/recipe_detail.html",
        {
            "recipe": recipe,
            "comments": comments,
            "form": form,
            "rating_form": rating_form,
            "average_rating": average_rating,
            "similar_recipes": similar_recipes,
            "total_views": total_views,
        },
    )


@require_POST
def rate_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id, status=Recipe.Status.PUBLISHED)

    if request.method == "POST":
        form = RatingForm(request.POST)
        if form.is_valid():
            rating, created = Rating.objects.update_or_create(
                recipe=recipe,
                user=request.user,
                defaults={"score": form.cleaned_data["score"]},
            )
            return render(
                request,
                "recipes/recipe/rate_recipe.html",
                {"rating": rating, "recipe": recipe},
            )
    else:
        form = RatingForm()

    return render(
        request,
        "recipes/recipe/rate_recipe.html",
        {"rating_form": form, "recipe": recipe},
    )


@require_POST
def recipe_comment(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id, status=Recipe.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = RecipeCommentForm(data=request.POST)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the recipe to the comment
        comment.recipe = recipe
        # Save the comment to the database
        comment.save()

    return render(
        request,
        "recipes/recipe/comment.html",
        {"recipe": recipe, "form": form, "comment": comment},
    )


def recipe_share(request, recipe_id):
    # Retrieve post by id
    recipe = get_object_or_404(Recipe, id=recipe_id, status=Recipe.Status.PUBLISHED)
    sent = False
    if request.method == "POST":
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(recipe.get_absolute_url())
            subject = (
                f"{cd['name']} ({cd['email']}) " f"recommends you read {recipe.title}"
            )
            message = (
                f"Read {recipe.title} at {post_url}\n\n"
                f"{cd['name']}'s comments: {cd['comments']}"
            )
            send_mail(
                subject=subject,
                message=message,
                from_email=None,
                recipient_list=[cd["to"]],
            )
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request,
        "recipes/recipe/recipe_share.html",
        {"recipe": recipe, "form": form, "sent": sent},
    )


@login_required
@require_POST
def recipe_like(request):
    recipe_id = request.POST.get("id")
    action = request.POST.get("action")
    if recipe_id and action:
        try:
            recipe = Recipe.objects.get(id=recipe_id)
            if action == "like":
                recipe.users_like.add(request.user)
                create_action(request.user, "likes", recipe)
            else:
                recipe.users_like.remove(request.user)
            return JsonResponse({"status": "ok"})
        except Recipe.DoesNotExist:
            pass
    return JsonResponse({"status": "error"})

myshop/recipes/templates/recipes/recipe/comment.html
{% extends "recipes/base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
  {% if comment %}
    <h2>Your comment has been added.</h2>
    <p><a href="{{ recipe.get_absolute_url }}">Back to the recipe</a></p>
  {% else %}
    {% include "recipes/recipe/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

myshop/recipes/templates/recipes/recipe/rate_recipe.html
{% extends "recipes/base.html" %}
{% block title %}Add a Rating{% endblock %}

{% block content %}
  {% if rating %}
    <h2>Your rating has been added.</h2>
    <p><a href="{{ recipe.get_absolute_url }}">Back to the recipe</a></p>
  {% else %}
    {% include "recipes/recipe/includes/rate_recipe_form.html" %}
  {% endif %}
{% endblock %}

myshop/recipes/templates/recipes/recipe/recipe_detail.html
{% extends "recipes/base.html" %}

{% block title %}{{ recipe.title }}{% endblock %}
{% block content %}
    <h1>{{ recipe.title }}</h1>
    <p class="date">
        Published {{ recipe.publish }} by {{ recipe.author }}
    </p>
 
   <!-- Images associated with the recipe -->
   <div class="recipe-image">
     {% for image in recipe.images.all %}
         <div class="image">
            <a href="{{ image.get_absolute_url }}">
                <img src="{{ image.image.url }}" alt="{{ image.description }}"  class="image-detail">
            </a>
             <p>{{ image.description }}</p>
             <!--
             {% load thumbnail %}
             <a href="{{ image.image.url }}">
               <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
             </a>
             -->
         </div>
     {% empty %}
         <p>No images available for this recipe.</p>
     {% endfor %}
    </div>

    <!-- Like button and count for the recipe -->
    {% with total_likes=recipe.users_like.count users_like=recipe.users_like.all %}
      <div class="recipe-info">
        <div>
            <span class="count">
                <span class="total">{{ total_likes }}</span>
                like{{ total_likes|pluralize }}
                </span>
                <span class="count">
                {{ total_views }} view{{ total_views|pluralize }}
            </span>
          <a href="#" data-id="{{ recipe.id }}" data-action="{% if request.user in users_like %}un{% endif %}like"
             class="like button">
            {% if request.user not in users_like %}
              Like
            {% else %}
              Unlike
            {% endif %}
          </a>
        </div>
      </div>
      <div class="image-likes">
        {% for user in recipe.users_like.all %}
          <div>
            {% if user.profile.photo %}
              <img src="{{ user.profile.photo.url }}">
            {% endif %}
            <p>{{ user.first_name }}</p>
          </div>
        {% empty %}
          Nobody likes this image yet.
        {% endfor %}
      </div>
    {% endwith %}

    <div class="recipe-detail">
        <h2>Ingredients: </h2>
        <p>
            <ul>
            {% for ingredient in recipe.ingredients.splitlines %}
                <li>{{ ingredient }}</li>
            {% endfor %}
            </ul>
        </p>
        <p>
            Preparation Time: {{ recipe.prep_time }} minutes
        </p>
        <p>
            Cooking Time: {{ recipe.cook_time }} minutes
        </p>
        <p>
            Average Rating: {{ recipe.average_rating|default_if_none:"Not Rated" }} / 5
        </p>
        <div>
        {% include "recipes/recipe/includes/rate_recipe_form.html" %}
        </div>
        <div style="clear:both"></div>
        <h2>Instructions:</h2>
        {{ recipe.body|linebreaks }}


        <p>
            <a href="{% url "recipes:recipe_share" recipe.id %}">
            Share this recipe
            </a>
        </p>

        <h2>Similar recipes</h2>
        {% for similar_recipe in similar_recipes %}
        <p>
            <a href="{{ similar_recipe.get_absolute_url }}">{{ similar_recipe.title }}</a>
        </p>
        {% empty %}
        There are no similar recipes yet.
        {% endfor %}

        {% with comments.count as total_comments %}
            <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
            </h2>
        {% endwith %}
        {% for comment in comments %}
            <div class="comment">
                <p class="info">
                Recipe comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
                </p>
                {{ comment.body|linebreaks }}
            </div>
        {% empty %}
        <p>There are no comments.</p>
        {% endfor %}
        {% include "recipes/recipe/includes/comment_form.html" %}
    </div>
{% endblock %}

{% block domready %}
  const url = '{% url "recipes:recipe_like" %}';
  var options = {
    method: 'POST',
    headers: {'X-CSRFToken': csrftoken},
    mode: 'same-origin'
  }

  document.querySelector('a.like')
          .addEventListener('click', function(e){
    e.preventDefault();
    var likeButton = this;

    // add request body
    var formData = new FormData();
    formData.append('id', likeButton.dataset.id);
    formData.append('action', likeButton.dataset.action);
    options['body'] = formData;

    // send HTTP request
    fetch(url, options)
    .then(response => response.json())
    .then(data => {
      if (data['status'] === 'ok')
      {
        var previousAction = likeButton.dataset.action;

        // toggle button text and data-action
        var action = previousAction === 'like' ? 'unlike' : 'like';
        likeButton.dataset.action = action;
        likeButton.innerHTML = action;

        // update like count
        var likeCount = document.querySelector('span.count .total');
        var totalLikes = parseInt(likeCount.innerHTML);
        likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
      }
    })
  });
{% endblock %}

myshop/recipes/templates/recipes/recipe/recipe_form.html
{% extends "recipes/base.html" %}

{% block title %}Create or Edit Recipe{% endblock %}

{% block content %}
    <h1>{% if form.instance.pk %}Edit Recipe{% else %}Create New Recipe{% endif %}</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">{% if form.instance.pk %}Update Recipe{% else %}Create Recipe{% endif %}</button>
    </form>

    <p>
        <a href="{% url 'recipes:recipe_list' %}">Back to Recipe List</a>
    </p>
{% endblock %}

myshop/recipes/templates/recipes/recipe/recipe_list.html
{% extends "recipes/base.html" %}
{% block title %}My Recipe Collection{% endblock %}
{% block content %}
    <h1>My Recipe Collection</h1>
    {% if tag %}
        <h2>Recipes tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for recipe in recipes %}
        <div class="recipe-entry">
            <div class="recipe-list">
                {% if recipe.images.all %}
                    <!-- Display the first image associated with the recipe -->
                    <a href="{{ recipe.get_absolute_url }}">
                        <img src="{{ recipe.images.all.0.image.url }}" alt="{{ recipe.images.all.0.description }}">
                    </a>
                {% else %}
                    <p>No image available</p>
                {% endif %}
            </div>

            <div class="recipe-details">
                <h2>
                <a href="{{ recipe.get_absolute_url }}">
                    {{ recipe.title }}
                </a>
                </h2>
                {% if recipe.is_premium %}
                    <span class="premium-label">Premium Recipe</span>
                {% endif %}
                <p class="tags">Tags: 
                    {% for tag in recipe.tags.all %}
                    <a href="{% url 'recipes:recipe_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                    </a>{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                <p class="date">
                    Published {{ recipe.publish }} by {{ recipe.author }}
                </p>
                <p>
                    Average Rating: {{ recipe.average_rating }} / 5
                </p>
                {% if recipe.is_premium %}
                    {% if user.is_authenticated and user.paid_user.is_paid %}
                        <p>Ingredients: {{ recipe.ingredients|truncatewords:10|linebreaks }}</p>
                        <p>Preparation Time: {{ recipe.prep_time }} minutes</p>
                    {% else %}
                        <p>This is premium content. <a href="{% url 'shop:payment_required' %}">Upgrade to premium</a> to access this recipe.</p>
                    {% endif %}
                {% else %}
                    <p>Ingredients: {{ recipe.ingredients|truncatewords:10|linebreaks }}</p>
                    <p>Preparation Time: {{ recipe.prep_time }} minutes</p>
                {% endif %}
                {{ recipe.content|truncatewords:30|linebreaks }}
            </div>
        </div>
    {% empty %}
        <li>No recipes available.</li>
    {% endfor %}
    {% include "pagination.html" with page=recipes %}
{% endblock %}

myshop/recipes/templates/recipes/recipe/recipe_share.html
{% extends "recipes/base.html" %}
{% block title %}Share {{ recipe.title }}{% endblock %}
{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ recipe.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
    {% else %}
    <h1>Share "{{ recipe.title }}" by e-mail</h1>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}