myshop/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    # post views
    path("", views.post_list, name="post_list"),
    # path("", views.PostListView.as_view(), name="post_list"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    path("search/", views.post_search, name="post_search"),
    # path("recipes/", views.recipe_list, name="recipe_list"),
    # path("recipes/tag/<slug:tag_slug>/", views.recipe_list, name="recipe_list_by_tag"),
    # path("recipes/<int:post_id>/", views.recipe_detail, name="recipe_detail"),
    # path(
    #     "recipes/<int:year>/<int:month>/<int:day>/<slug:recipe>/",
    #     views.recipe_detail,
    #     name="recipe_detail",
    # ),
    # path("recipes/<int:recipe_id>/rate/", views.rate_recipe, name="rate_recipe"),
    # path("recipes/<int:recipe_id>/share/", views.recipe_comment, name="recipe_comment"),
    # path(
    #     "recipes/<int:recipe_id>/comment/", views.recipe_comment, name="recipe_comment"),
]

myshop/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

myshop/images/urls.py
from django.urls import path
from . import views

app_name = "images"
urlpatterns = [
    path("create/", views.image_create, name="create"),
    path("detail/<int:id>/<slug:slug>/", views.image_detail, name="detail"),
    path("like/", views.image_like, name="image_like"),
    path("", views.image_list, name="list"),
    path("ranking/", views.image_ranking, name="ranking"),
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from payment import webhooks

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path(_("cart/"), include("cart.urls", namespace="cart")),
    path(_("orders/"), include("orders.urls", namespace="orders")),
    path(_("payment/"), include("payment.urls", namespace="payment")),
    path(_("coupons/"), include("coupons.urls", namespace="coupons")),
    path("rosetta/", include("rosetta.urls")),
    path(_("account/"), include("account.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path(_("images/"), include("images.urls", namespace="images")),
    path("__debug__/", include("debug_toolbar.urls")),
    path(_("blog/"), include("blog.urls", namespace="blog")),
    path(_("recipes/"), include("recipes.urls", namespace="recipes")),
    path("", include("shop.urls", namespace="shop")),
)
urlpatterns += [
    path("payment/webhook/", webhooks.stripe_webhook, name="stripe-webhook"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/recipes/urls.py
from django.urls import path
from . import views

app_name = "recipes"
urlpatterns = [
    # post views
    path("", views.recipe_list, name="recipe_list"),
    # path("", views.PostListView.as_view(), name="post_list"),
    path("tag/<slug:tag_slug>/", views.recipe_list, name="recipe_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:recipe>/",
        views.recipe_detail,
        name="recipe_detail",
    ),
    path("<int:recipe_id>/rate/", views.rate_recipe, name="rate_recipe"),
    path("<int:recipe_id>/share/", views.recipe_share, name="recipe_share"),
    path("<int:recipe_id>/comment/", views.recipe_comment, name="recipe_comment"),
    path("like/", views.recipe_like, name="recipe_like"),
]

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"
urlpatterns = [
    path("payment-required/", views.payment_required, name="payment_required"),
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
]

myshop/shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["name"]),
        ]
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["id", "slug"]),
            models.Index(fields=["name"]),
            models.Index(fields=["-created"]),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])

myshop/shop/views.py
from django.shortcuts import get_object_or_404, render
from .models import Category, Product
from cart.forms import CartAddProductForm
from .recommender import Recommender
from django.shortcuts import redirect
from django.urls import reverse


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(
        request,
        "shop/product/list.html",
        {"category": category, "categories": categories, "products": products},
    )


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)
    return render(
        request,
        "shop/product/detail.html",
        {
            "product": product,
            "cart_product_form": cart_product_form,
            "recommended_products": recommended_products,
        },
    )


def payment_required(request):
    product_id = 5
    slug = "premium-recipes"

    product_url = reverse("shop:product_detail", args=[product_id, slug])
    print("Redirecting to:", product_url)
    return redirect(product_url)

myshop/shop/templates/shop/base.html
{% load i18n static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}{% translate "My shop" %}{% endblock %}</title>
    <link href="{% static "css/base-shop.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">{% translate "My shop" %}</a>
      {% get_current_language as LANGUAGE_CODE %}
      {% get_available_languages as LANGUAGES %}
      {% get_language_info_list for LANGUAGES as languages %}
      <div class="languages">
        <p>{% translate "Language" %}:</p>
        <ul class="languages">
          {% for language in languages %}
            <li>
              <a href="/{{ language.code }}/"
              {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %}>
                {{ language.name_local }}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
      {% if request.user.is_authenticated %}
      <ul class="menu">
        <li {% if section == "dashboard" %}class="selected"{% endif %}>
          <a href="{% url "dashboard" %}">My dashboard</a>
        </li>
        <li {% if section == "images" %}class="selected"{% endif %}>
          <a href="{% url "images:list" %}">Images</a>
        </li>
        <li {% if section == "people" %}class="selected"{% endif %}>
          <a href="{% url "user_list" %}">People</a>
        </li>
        <li {% if section == "blog" %}class="selected"{% endif %}>
          <a href="{% url "blog:post_list" %}">Blog</a>
        </li>
        <li {% if section == "recipes" %}class="selected"{% endif %}>
          <a href="{% url "recipes:recipe_list" %}">Recipes</a>
        </li>
        <li {% if section == "search" %}class="selected"{% endif %}>
          <a href="{% url "blog:post_search" %}">Search</a>
        </li>
        <li {% if section == "shop" %}class="selected"{% endif %}>
          <a href="{% url "shop:product_list" %}">Shop</a>
        </li>
        <li {% if section == "admin" %}class="selected"{% endif %}>
          <a href="{% url "admin:index" %}">Admin</a>
        </li>
      </ul>
      {% endif %}
    </div>
    <div id="subheader">
      <div class="cart">
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            {% translate "Your cart" %}:
            <a href="{% url "cart:cart_detail" %}">
              {% blocktranslate with total=cart.get_total_price count items=total_items %}
                {{ items }} item, ${{ total }}
              {% plural %}
                {{ items }} items, ${{ total }}
              {% endblocktranslate %}
            </a>
          {% elif not order %}
            {% translate "Your cart is empty." %}
          {% endif %}
        {% endwith %}
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>